// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_paths`

/// [FRB] 获取 hosts 文件所在的目录路径，供 UI 调用
String getHostsDir() => RustLib.instance.api.crateApiIoGetHostsDir();

/// [FRB] 备份当前的 hosts 文件
Future<String> saveCurrentHosts() =>
    RustLib.instance.api.crateApiIoSaveCurrentHosts();

/// [FRB]【新功能】从备份文件还原 hosts
Future<String> revertHosts() => RustLib.instance.api.crateApiIoRevertHosts();

/// 【新格式】智能更新 hosts 文件，为不同目标创建独立区块
Future<void> updateHostsFile({
  required OptimizationTarget target,
  required List<(String, String)> optimizedHosts,
}) => RustLib.instance.api.crateApiIoUpdateHostsFile(
  target: target,
  optimizedHosts: optimizedHosts,
);

/// 这是一个未被优选流程使用，但可能被FRB引用的辅助函数。
/// 为了安全起见，我们保留它。
Future<String> saveContentToFile({
  required String filename,
  required String content,
}) => RustLib.instance.api.crateApiIoSaveContentToFile(
  filename: filename,
  content: content,
);
