// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_ips_via_doh`, `get_domains_for_target`, `ping_ip`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DohAnswer`, `DohResponse`, `DomainList`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 主优化函数，暴露给 Flutter 调用。
Future<String> optimizeHosts({required OptimizationTarget target}) =>
    RustLib.instance.api.crateApiOptimizerOptimizeHosts(target: target);
